//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tms.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int Id { get; set; }
        public Nullable<int> MovieId { get; set; }
        public string Name { get; set; }
        public string Language { get; set; }
        public string OttPlatform { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> TrailerDate { get; set; }
        public Nullable<System.DateTime> TeaserDate { get; set; }
        public Nullable<System.DateTime> OttReleaseDate { get; set; }
        public string Image { get; set; }
        public Nullable<bool> IsUploadedToTelegram { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
